### ISSUE TITLE
pano tool - Unable to open file '/tmp/tmp.4VL5Wv4sQr/split-0.tif'

### ISSUE THREAD

**Issue by joseccnet** [ultramango/gear360pano#1]
Hi! I'm running you tool in Windows 10. yes!! :)

Im using cygwin, Hugin for windows installer and dependencies.

$ export PATH=$PATH:/cygdrive/c/Program\ Files\ \(x86\)/Hugin/bin

But there is an error on running gear360pano.sh

```
$ ./gear360pano.sh 360_0001.JPG
Splitting input image
Processing input images
caught exception:
Precondition violation!
Unable to open file '/tmp/tmp.4VL5Wv4sQr/split-0.tif'.
(d:/Works/vigra-1.11.0/src/impex/codecmanager.cxx:203)

Error when running nona
```

So, the solution I found is simple:

```
$ diff gear360pano.sh.ori gear360pano.sh
41c41,42
< TEMPDIR=`mktemp -d`
---
> if [ ! -d ./tmp ] ; then mkdir ./tmp; fi
> TEMPDIR=`mktemp -d -p ./tmp`
```

Can you include this change? Thanks a lot!

Excelent tool !!!

**Comment by ultramango** [comment]
Hi!

I added Windows compatibility (slightly modified your patch) plus you don't need to add Hugin to your path. Temporary directory is now created in local directory - not super elegant, but if it helps Hugin for Windows... The problem was that cygwin path was not accepted by Hugin, the modification makes the temporary path relative which works.
