### ISSUE TITLE
Twice the size as ActionDirector and less quality

### ISSUE THREAD

**Issue by TheNetStriker** [ultramango/gear360pano#11]
I've compared the image stiching of ActionDirector and this script. The image stiched by the script was almost twice the size of the ActionDirector file. (12 MB instead of 6 MB)
Also the image quality is not as good as in ActionDirector. When zooming in on one of the images from the script the picture gets very pixelated. On the image from ActionDirector the images are much smoother. (Maybe due to interpolation?)

Could this be improoved or is this just not possible using those sitching tools?

**Comment by ultramango** [comment]
The size is dictated by the resulting JPEG quality and can be changed inside script (look for '''JPGQUALITY''').

The quality (pixelation) might be due to some other problem that is affecting you, based on other cases that you've created. Please provide source files so I can reproduce the problem. I assume that you're using the tool under Windows.

Overall quality could be improved, but there might be a fundamental difference between ActionDirector and Hugin solution. ActionDirector *might* dynamically find control points and do some dynamic adjustments, in case of this particular project transformation data is static and might not fit well all the cameras. If you're willing to do manual adjustments - see my other answers to your issues.

Once I'll have my main machine (it is being repaired) running I'll try to prepare a better template.
