### ISSUE TITLE
Command Not Found in Mac

### ISSUE THREAD

**Issue by paulyuatgithub** [ultramango/gear360pano#33]
Hi,

After installation, path modification on .bash_profile, and chmod the gear360pano.cmd to executable, I tried to run your script in Mac. 

However, I got 
"-bash: gear360pano.cmd: command not found"

Do you know why ?
Thanks,
Paul

**Comment by durkie** [comment]
this sounds like a path issue. two things to figure out:
* where is gear360pano.cmd located? keep track of this for 👇 
* what does `which gear360pano.cmd` say? that will look everywhere in your $PATH variable to find gear360pano.cmd, so if `which` returns nothing then you can either put gear360pano.cmd in a directory that's in your path (/usr/local/bin is a decent candidate, or call gear360pano.cmd by its full path (the one that you found in the first point)

**Comment by ultramango** [comment]
Hi,

Since I have now access to a Mac I will check it.

Just a wild, dumb guess, did you run the script like this (mind the dot and slash)?

    ./gear360pano.cmd

On *nix systems, usually, current directory (```.```) is not in the path. So if you try to run the script directly (```gear360pano.cmd```) it will not work.

Another guess is that Mac doesn't like the trickery with having Windows and Linux version in the same file. Second semi-random fix: add ```#!/usr/bin/env bash``` or ```#!/bin/bash``` at the very beggining of the file.

**Comment by durkie** [comment]
The Win/Linux version in the same file isn't an issue -- I'm running it on a mac no problem.

**Comment by ultramango** [comment]
@paulyuatgithub - do you still have the problem with running the script on Mac?

**Comment by ultramango** [comment]
No update on the case - assuming no longer a problem.
