### ISSUE TITLE
Inverted photo

### ISSUE THREAD

**Issue by juda73** [ultramango/gear360pano#6]
Centered image is reversed.

**Comment by ultramango** [comment]
Please provide more details of the problem, for example: example input and output image.

**Comment by juda73** [comment]
![example](https://cloud.githubusercontent.com/assets/22507684/18935552/1ea85814-85e1-11e6-949f-a7b73fc7108a.JPG)

**Comment by ultramango** [comment]
Thanks for the detailed description. Looks like original software does a better job at stitching - proper vertical lines. BTW: inverted means for me with inverted colours or upside-down.

I see no serious problem with script generating "shifted" panorama. There's a possibility to "shift"/"rotate" final panorama while stitching in Hugin. The only advantage would be to be in line with the original software. I'll see if I can make a better template file and perhaps also mimic the original Samsung software.

Note: that I don't have access to original app (it doesn't work on my "old" phone), that's why I created this script in the first place.

**Comment by juda73** [comment]
Thank for your good work, I do not know how to use Hugin well, your writing is very helpful with lots of photos
Sorry for my english.

**Comment by juda73** [comment]
I have tried to invert the name of file in gear360pano2.cmd with no success, is the pto file to modify?

```
`echo "Stitching input images (enblend)"
cmd="enblend -o $OUTNAME \
     --compression=jpeg:$JPGQUALITY \
     $TEMPDIR/${OUTTMPNAME}0001.tif \
     $TEMPDIR/${OUTTMPNAME}0000.tif"
run_command $cmd`
```

**Comment by ultramango** [comment]
Do this:

1. Rename your panorama to dummy.jpg (the one coming from Gear360).
2. Start Hugin and open ```gear360tmpl.pto``` file (it will open your panorama file).
3. Go to Fast Preview Panorama (icon with "GL").
4. Select "Move/Drag" tab.
5. As Drag Mode select "Normal".
6. Using left click you can shift panorama around using left click.

You should be able to make it similar to original Samsung stitcher.

**Comment by juda73** [comment]
Great!! Thanks
